### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by dirkk0**
added transformers and uglify-js.

### CODE REVIEW

**Comment by fnakstad** [comment]
Hi Dirk, and thank you for the pull request :)
It looks like the commit only contains updates to `package.json`...
Where's the code that actually uses these libraries?

**Comment by dirkk0** [comment]
I don't know - I didn't create any code (yet). I only installed your git and just figured out that I (i.e. your code) needed these libraries that I added manually in the first run.

**Comment by fnakstad** [comment]
Ah, I see. 
So, if you want to customize the project for your own purposes you should fork the repo first. That way you have your own isolated branch of the code that doesn't affect what's going on in my branch.

**Comment by dirkk0** [comment]
I know and thank you - but if you check out your project on a fresh installation you will see that these libs are missing :-).

**Comment by fnakstad** [comment]
Well, I tried cloning a fresh copy on a computer I previously hadn't pulled the project to, and everything worked fine after doing a simple `npm install`. Besides, I'm 100% sure I don't have a "direct" dependency on these libraries. I do see that some of the other libraries I'm using have dependencies on transformers and uglify-js, however they should be installed recursively by npm. Could I ask you what command you used to install the dependencies?

**Pull request closed without merging**
